### ISSUE TITLE
float in key value

### ISSUE THREAD

**Issue by tvernick** [JonnoFTW/mongo-schema-export#1]
Hi there- Any idea why I would be getting a float value from the key when exporting?
The value is just "phone" : 1 in mongo.
For example:
`                    {
                        "name": "phone_1",
                        "background": true,
                        "keys": [
                            [
                                "phone",
                                1.0
                            ]
                        ]
                    }
                ],
                "options": {}
`

**Comment by JonnoFTW** [comment]
What version of python are you running?

Regardless, I'll push a fix to ensure all keys are exported as `int`

**Comment by tvernick** [comment]
python 3.6
Appreciate that thanks!

**Comment by JonnoFTW** [comment]
What versions of pymongo and mongodb?

**Comment by tvernick** [comment]
Whatever is most recent python 3 pymongo and mongo 3.6.6

**Comment by JonnoFTW** [comment]
@tvernick Please test the fix by running `pip install -U mongo-schema-export`

It should place the scripts in your bin directory of your python install, so you should now be able to run

```
mongo-schema-export.py ...
```

**Comment by tvernick** [comment]
Works great, thanks!

**Comment by tvernick** [comment]
I see to be getting another error from that change now

Traceback (most recent call last):
  File "export_mongo.py", line 88, in <module>
    sys.exit(main() or 0)
  File "export_mongo.py", line 82, in main
    s = mongo_export(_client, args.file, args.databases, args.verbose)
  File "export_mongo.py", line 38, in mongo_export
    i['keys'] = [[k, int(v)] for k, v in i['key'].items()]
  File "export_mongo.py", line 38, in <listcomp>
    i['keys'] = [[k, int(v)] for k, v in i['key'].items()]
ValueError: invalid literal for int() with base 10: 'hashed'

Looks like this won't work if the sort is called "hashed".

**Comment by JonnoFTW** [comment]
@tvernick I've pushed a fix. Please try it and report back results
