### ISSUE TITLE
Support import on existing collections (with no dropping or creating)

### ISSUE THREAD

**Issue by ericbn** [JonnoFTW/mongo-schema-export#2]
`mongo-schema-import.py` still tries to create the collection even if no `--delete-col` is provided. It would be nice to support importing over existing collections (in case I want to import the data first, and then the "schema" afterwards, instead of the other way around).

Currently it fails with:
```
Creating database: mydatabase
	Creating collection: mycollection
		Options {}
Traceback (most recent call last):
  File "mongo-schema-import.py", line 79, in <module>
    sys.exit(main() or 0)
  File "mongo-schema-import.py", line 75, in main
    mongo_import(_client, args.file, args.delete_db, args.delete_col, args.databases, args.verbose)
  File "mongo-schema-import.py", line 42, in mongo_import
    collection = db.create_collection(cname, **c['options'])
  File "venv/lib/python3.7/site-packages/pymongo/database.py", line 365, in create_collection
    raise CollectionInvalid("collection %s already exists" % name)
pymongo.errors.CollectionInvalid: collection mycollection already exists
```

**Comment by JonnoFTW** [comment]
Thanks for this, I'll make the change and push a fix.
